### PR TITLE
[2522] - feat(security): add Brakeman static analysis

### PR DESCRIPTION
**Pull request by TobyRet**
### Context
Static analysis is way to identifies security flaws in an application. _Brakeman_ is a gem that provides this functionality.

### Changes proposed in this pull request
- Add Brakeman gem
- Create rake task to run static analysis locally
- Add Brakeman rake task to default rake task
- Add static analysis as a build step on CI. Build will fail if static analysis does not pass.

### Running locally
```
bundle exec brakeman
```

#### Local output

brakman

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by TobyRet** [comment]
[Scan our apps for security vulnerabilities](https://trello.com/c/hz2zYzrk/2522-scan-our-apps-for-security-vulnerabilities)

**Comment by defong** [comment]
Looking good any chance we can add it to the

Git check
image

or azure, next to tests 
image

**Comment by TobyRet** [comment]
> Looking good any chance we can add it to the
> 
> Git check
> image
> 
> or azure, next to tests
> image

I asked Riz if we could have multistage pipelines but currently this is not possible sorry
[GitHub - MicrosoftDocs/pipelines-multistage: Multi-stage samples for Azure Pipelines](https://github.com/MicrosoftDocs/pipelines-multistage)

**Comment by TobyRet** [comment]
[Scan our apps for security vulnerabilities](https://trello.com/c/hz2zYzrk/2522-scan-our-apps-for-security-vulnerabilities)

**Comment by defong** [comment]
is it me or its really hard to read

image

**Comment by timabell** [comment]
@defong those look like raw console colour codes

**Pull request merged**
