### PR TITLE
[1856] Set application start and end date to not null

### PR DESCRIPTION
**Pull request by davidgisbey**
### Context
The update applications open logic is reliant on these columns being populated.

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by davidgisbey** [comment]
[[S] Edit 'Course Applications Open' - (MCBE)](https://trello.com/c/p2P5U9L2/1856-s-edit-course-applications-open-mcbe)

**Comment by defong** [comment]
you have done the migration to back fill the data right?

**Comment by davidgisbey** [comment]
Yes. That's already been added in the previous migration.

**Comment by timabell** [comment]
> The update applications open logic is reliant on these columns being populated.

imho this should be in the commit message too so you can find it with `git blame`

**Pull request merged**
