### PR TITLE
[1036] Amended default port to be used from 3000 to 3001

### PR DESCRIPTION
**Pull request by defong**
### Context
Post collision with its client, since client port change has external factors involved, its done here instead.

### Changes proposed in this pull request
Amended default port to be used from 3000 to 3001

### Guidance to review
Client should now be in a position to be seeded with default values for development.

Soon rather than later it be nice to have the 2 rails chatting with one and another.

### CODE REVIEW

**Comment by defong** [comment]
Port number is always going to be a debacle.
Just any number that's not 3xxx is fine, better have it out here so the overall communication.

80 is http, 433 is https, 3000, is neither 3080 or 3433, so the 3xxx is out of bounds.

**Comment by defong** [comment]
normally default port number are simply not used

as when you wanna take a sample out to have a look see, you screwed, particular with favicon,

first 2048 port number is out of bounds due to system needs

so pick a number and see if someone wanna fight over it

i picked mine, so stick or twist.

**Comment by defong** [comment]
[Backend port 3000 to 30000](https://trello.com/c/qBGXA3hE/1036-backend-port-3000-to-30000)

**Comment by defong** [comment]
To make it easier the, below port number cannot chosen.

666
3xxx
5xxx
6xxx
43xxx

The passing mark, is xxx is details. 

So a quick question of xx thousand port is used by x default app.

**Comment by misaka** [comment]
Why is 3xxx out?

With 7 services running now, I agree it'd be nice to have a different standard port for each, something like:

3001 - manage-courses-ui
3002 - manage-courses-ui
3003 - search-and-compare-ui
3004 - search-and-compare-api
3005 - manage-courses-support
3006 - manage-courses-frontend
3007 - manage-courses-backend

**Comment by dankmitchell** [comment]
Okay, I give in. In this instance i'd just specify the port `rails s -p 3001` because as a rails developer I always expect the app to run over port `3000`.

Can we go with `3001`, please?

**Comment by defong** [comment]
I'm reluctant to make wholesale changes, and additional dependencies will be incurred. 

ie
manage-courses-ui
manage-courses-frontend

I stick with `3001` for `manage-courses-backend` if there is no more debates

**Comment by misaka** [comment]
@defong Had a think about this overnight and I think 3001 for `manage-courses-backend` is the right thing to do.

**Pull request merged**
