### PR TITLE
[1496] Use site.save instead of save! when creating

### PR DESCRIPTION
**Pull request by tvararu**
### Context

Adding new locations.

### Changes proposed in this pull request

This stop the backend from blowing up and instead sending down the validation errors.

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by tvararu** [comment]
[New training location form: validations](https://trello.com/c/L5dCY5nT/1496-new-training-location-form-validations)

**Comment by benilovj** [comment]
Are we missing specs that would have caught this?

**Comment by tvararu** [comment]
@benilovj yeah, I deliberately didn't copy+paste from the update tests because I thought "oh, everything is the same, why test it twice..."

**Comment by tvararu** [comment]
@benilovj added a spec

**Pull request merged**
