### PR TITLE
[2563] - Upgrade Rails to 6.0.1

### PR DESCRIPTION
**Pull request by TobyRet**
### Context
Dependabot tried and failed.
Now it's payback time.

### Changes proposed in this pull request
Upgrade Rails to 6.0.1

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally

### CODE REVIEW

**Comment by misaka** [comment]
@TobyRet https://github.com/DFE-Digital/manage-courses-backend/pull/984

**Comment by misaka** [comment]
@TobyRet Would you mind having a look to see if the problem described there is still a problem?

**Comment by defong** [comment]
https://github.com/DFE-Digital/manage-courses-backend/pull/984
https://github.com/DFE-Digital/manage-courses-backend/pull/986

for references

**Comment by TobyRet** [comment]
@misaka @defong 
Yep ran locally and I ran into the same problem

Rails 6.0.0
RecruitmentCycle.syncable_courses.count 
=> 12411

Rails 6.0.1
RecruitmentCycle.syncable_courses.count 
=> 11670

**Pull request closed without merging**
