### PR TITLE
2367 add validation for new courses

### PR DESCRIPTION
**Pull request by defong**
### Context
Validation for course

### Changes proposed in this pull request
Added validation for the presence of field where possible
Fixed the inferior level from the course factory

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by defong** [comment]
[[S] Add validation for new courses](https://trello.com/c/hIxIMfjp/2367-s-add-validation-for-new-courses)

**Comment by danielburnley** [comment]
Notes from testing frontend:

### Level
- The error given is "There is a problem with this course. Contact support to fix it (Error: L)"
    - Feels oddly worded for new courses

### Age Range in years
- Missing

### Funding type (apprenticeship & fee/salaried)
- Missing

### Entry requirements (science, maths, english)
- Duplicate error messages

```
    Maths can't be blank
    Pick an option for Maths
    English can't be blank
    Pick an option for English
    Science can't be blank
    Pick an option for Science
```

### Applications open from
- Missing

**Comment by defong** [comment]
#### Level
- Fixed via validation message differing based on `:publish` or `:create`
 
#### Age Range in years
- Fixed via validation on `:create`

#### Entry requirements (science, maths, english)
- Fixed by favouring `Pick an option xxx`

#### Not fixing 
##### Funding type (apprenticeship & fee/salaried)
- This is a calculated value
##### Applications open from
- This is used in mcb

**Comment by danielburnley** [comment]
@defong although funding type is is calculated, it does have an `funding_type=` method which sets the `program_type`. Feels like to do validation on this might need something unpicking somewhere :thinking:

**Comment by defong** [comment]
> @defong although funding type is is calculated, it does have an `funding_type=` method which sets the `program_type`. Feels like to do validation on this might need something unpicking somewhere thinking

Yeha, maybe we consider the `funding_type` and `program_type` usage and refactor it to be nicer...

**Comment by danielburnley** [comment]
Feels like refactoring should be it's own task - Wanna start doing the FE task for these validations so having a starting point merged would be good even if it doesn't catch everything (though we should log somewhere what validations remain)

**Comment by defong** [comment]
Carded up the two fields in question
https://trello.com/c/PxA5UD6j/2422-add-validations-for-funding-type-for-when-creating-a-new-course
https://trello.com/c/kY4sH57Y/2423-add-validations-for-applications-open-from-for-when-creating-a-new-course

as they quite more complex then the ones here

**Pull request merged**
