### PR TITLE
[2709] - Re-enable Redis caching for storing geocoder api responses

### PR DESCRIPTION
**Pull request by TobyRet**
### Context
Redis caching for geocoding was turned off recently when we were debugging Postgres connection issues on QA. Just need to enable again

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by TobyRet** [comment]
[Turn on Redis caching for Geocoding](https://trello.com/c/HeL8iUuT/2709-turn-on-redis-caching-for-geocoding)

**Comment by TobyRet** [comment]
[Turn on Redis caching for Geocoding](https://trello.com/c/HeL8iUuT/2709-turn-on-redis-caching-for-geocoding)

**Comment by TobyRet** [comment]
[Turn on Redis caching for Geocoding](https://trello.com/c/HeL8iUuT/2709-turn-on-redis-caching-for-geocoding)

**Comment by TobyRet** [comment]
[Turn on Redis caching for Geocoding](https://trello.com/c/HeL8iUuT/2709-turn-on-redis-caching-for-geocoding)

**Comment by dankmitchell** [comment]
[Turn on Redis caching for Geocoding](https://trello.com/c/HeL8iUuT/2709-turn-on-redis-caching-for-geocoding)

**Pull request merged**
