### PR TITLE
[2541] Remove redundant MCB functionality

### PR DESCRIPTION
**Pull request by davidgisbey**
### Context

MCB now replicates quite a bit of functionality that can be completed via publish.

### Changes proposed in this pull request

- Remove grant admin access
- Remove functionality from the course editor

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by benilovj** [comment]
🔥 🔥 🔥 🔥 🔥 🔥

**Comment by davidgisbey** [comment]
[Remove functionality from MCB that can be done in the UI now](https://trello.com/c/lI2us7vy/2541-remove-functionality-from-mcb-that-can-be-done-in-the-ui-now)

**Comment by TobyRet** [comment]
@davidgisbey - Interesting that coverage has decreased (reason for the build failure). The SimpleCov threshold is 75% and it's only this low because of (apparent) lack of coverage in mcb console. If mcb is deprecated perhaps it could be worth excluding the mcb files in simplecov (and Code Climate)... might be worth a discussion?

**Comment by davidgisbey** [comment]
@TobyRet good idea. I think some of this really should be tested if we're going to continue to use it. Particularly the access wizard.

**Comment by davidgisbey** [comment]
After discussing with @dankmitchell we think it's best to remove mcb commands from Simplecov coverage for two reasons. 

1. MCB should be gone soon 
2. It would require a lot of time to add the coverage that would be required to bring the coverage % up.

**Pull request merged**
