### PR TITLE
[1673] Fixed broken forward motion due to required mandatory historical data changes

### PR DESCRIPTION
**Pull request by defong**
### Context
Broken forward motion due to required mandatory historical data changes
Before this PR left hand and right hand not working in sync.

### Changes proposed in this pull request
Fixed broken forward motion due to required mandatory historical data changes

### Guidance to review
https://github.com/DFE-Digital/manage-courses-backend/pull/506#discussion_r295655977

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by defong** [comment]
[Move data migrations that set recruitment_cycle on courses and sites to schema migrations](https://trello.com/c/T6tltYvv/1673-move-data-migrations-that-set-recruitmentcycle-on-courses-and-sites-to-schema-migrations)

**Comment by misaka** [comment]
Tried locally:

```
% rails db:migrate:status

database: manage_courses_backend_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20190213160920  Add changed at to provider
   up     20190222063449  Add opted in to provider
   up     20190227124613  Initialize provider changed at
   up     20190301114503  Add changed at to course
   up     20190306122110  Initialize course changed at
   up     20190313153617  Change changed at to unique
   up     20190319163755  Add provider UCAS preferences
   up     20190320144534  Create contact
   up     20190409230916  Install audited
   up     20190416093524  Add aasm state to users
   up     20190418114021  Change aasm state default and nullable on users
   up     20190507150812  Remove opted in from provider
   up     20190619114150  Create recruitment cycle
  down    20190619142449  Add recruitment cycle to course
  down    20190620060536  Set recruitment cycle to not null
  down    20190620120944  Add recruitment cycle to site
  down    20190621125905  Set site recruitment cycle to not null

% git checkout 1673-data-vs-schema-migrations-for-recruitment-cycle-id
Switched to branch '1673-data-vs-schema-migrations-for-recruitment-cycle-id'
Your branch is ahead of 'master' by 1 commit.
  (use "git push" to publish your local commits)

% rails db:migrate
== 20190619142449 AddRecruitmentCycleToCourse: migrating ======================
-- add_reference(:course, :recruitment_cycle, {:index=>true, :type=>:int})
   -> 0.0213s
== 20190619142449 AddRecruitmentCycleToCourse: migrated (0.0214s) =============

== 20190619144634 Add2019RecruitmentCycleToCourses: migrating =================
== 20190619144634 Add2019RecruitmentCycleToCourses: migrated (1.0137s) ========

== 20190620060536 SetRecruitmentCycleToNotNull: migrating =====================
-- change_column_null(:course, :recruitment_cycle_id, false)
   -> 0.0038s
== 20190620060536 SetRecruitmentCycleToNotNull: migrated (0.0038s) ============

== 20190620120944 AddRecruitmentCycleToSite: migrating ========================
-- add_reference(:site, :recruitment_cycle, {:index=>true, :type=>:int})
   -> 0.0093s
== 20190620120944 AddRecruitmentCycleToSite: migrated (0.0094s) ===============

== 20190620121519 Add2019RecruitmentCycleToSites: migrating ===================
== 20190620121519 Add2019RecruitmentCycleToSites: migrated (0.2018s) ==========

== 20190621125905 SetSiteRecruitmentCycleToNotNull: migrating =================
-- change_column_null(:site, :recruitment_cycle_id, false)
   -> 0.0022s
== 20190621125905 SetSiteRecruitmentCycleToNotNull: migrated (0.0023s) ========
```

**Comment by misaka** [comment]
Looks like the offending migrations have been run in `qa` but not `staging` (and by extension `production` either). This makes sense, the `recruitment_cycle` migrations would've run ok when being merged in from the PRs, but will blow up when we merge in all of them at the same time into `staging` and `production`.

I think we need to rollback `qa` before we merge this into `master` so as not to break it and to test it fully.

qa:
```
$ psql -h bat-qa-mcapi-psql.postgres.database.azure.com -U manage_courses@bat-qa-mcapi-psql -d manage_courses
psql (9.6.10, server 9.6.12)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

manage_courses=> select * from schema_migrations ;
    version
----------------
 20190213160920
 20190222063449
 20190227124613
 20190301114503
 20190306122110
 20190313153617
 20190319163755
 20190320144534
 20190409230916
 20190416093524
 20190418114021
 20190507150812
 20190619114150
 20190619142449
 20190620120944
 20190620060536
(16 rows)
```

staging:
```
psql -h bat-staging-manage-courses-psql.postgres.database.azure.com -U manage_courses@bat-staging-manage-courses-psql -d manage_courses
psql (9.6.10, server 9.6.12)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

manage_courses=> select * from schema_migrations ;
    version
----------------
 20190213160920
 20190222063449
 20190227124613
 20190301114503
 20190306122110
 20190313153617
 20190319163755
 20190320144534
 20190409230916
 20190416093524
 20190418114021
 20190507150812
(12 rows)
```

**Comment by dankmitchell** [comment]
@misaka this is my fault, I should have shepherded the table creation and first data migration PR's all the way to prod before adding the `not null` migration :(

Should we revert the not null commits i.e. https://github.com/DFE-Digital/manage-courses-backend/pull/523 && https://github.com/DFE-Digital/manage-courses-backend/pull/522 ?

**Comment by defong** [comment]
> @misaka this is my fault, I should have followed the table creation and first data migration PR's all the way to prod before adding the `not null` migration :(
> 
> Should we revert the not null commits i.e. #523 && #522 ?

Freight train is at full stream

**Comment by misaka** [comment]
> Should we revert the not null commits i.e. #523 && #522 ?

I don't think we should revert ... I think this is my fault for suggesting doing data migrations in the first place! tbh, I never was a fan, and it felt funny to me .. so I think we ditch the concept and just move forward with data migrations mixed in with the rest.

I happened to notice, while doing a bit of research for another data migration, that the Rails docs have quite a few references to doing data migrations alongside schema migrations so that's reassuring.

**Comment by smneal** [comment]
@misaka, @defong If it helps dev, qa are in a broken deployment state where the build has failed to run against them. New staging still has a green build deployed so may be an environment where the migrations haven't been run at all yet?

**Comment by tvararu** [comment]
On my machine, I have a weird `20190620132941  ********** NO FILE **********` migration:

```bash
$ rails db:migrate:status

database: manage_courses_backend_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20190213160920  Add changed at to provider
   up     20190222063449  Add opted in to provider
   up     20190227124613  Initialize provider changed at
   up     20190301114503  Add changed at to course
   up     20190306122110  Initialize course changed at
   up     20190313153617  Change changed at to unique
   up     20190319163755  Add provider UCAS preferences
   up     20190320144534  Create contact
   up     20190409230916  Install audited
   up     20190416093524  Add aasm state to users
   up     20190418114021  Change aasm state default and nullable on users
   up     20190507150812  Remove opted in from provider
   up     20190619114150  Create recruitment cycle
   up     20190619132129  Create recruitment cycles
   up     20190619142449  Add recruitment cycle to course
   up     20190619144634  Add 2019 recruitment cycle to courses
   up     20190620060536  Set recruitment cycle to not null
   up     20190620120944  Add recruitment cycle to site
   up     20190620121519  Add 2019 recruitment cycle to sites
   up     20190620132941  ********** NO FILE **********
   up     20190621125905  Set site recruitment cycle to not null
```

**Comment by misaka** [comment]
@tvararu That's just something on your system ... maybe a new migration you picked up and ran from another branch? I can't find evidence of it yet so I think it's more likely to be something you had locally.

**Comment by misaka** [comment]
@smneal I don't think we have to roll anything back, even in the broken envs. I *think*. This will be good to test, I think we should be able to merge this and then test in the environments you mention.

**Pull request merged**
