### PR TITLE
[1733] Add persistent history to MCB

### PR DESCRIPTION
**Pull request by faissalMT**
### Context
It's a lot easier to just hit up a few times than try to remember and type out a command.  

### Changes proposed in this pull request
Add a history file to `~/.mcb_history` which can be loaded.

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by faissalMT** [comment]
[Persist command history in mcb repl](https://trello.com/c/nxuny47M/1733-persist-command-history-in-mcb-repl)

**Comment by timabell** [comment]
works for me

```
cat ~/.mcb_history 
help
?
az
az -h
az apps psql
```

**Comment by timabell** [comment]
should probably test on mac too

**Comment by NyWeb** [comment]
Just tested on macOS, works here too

**Pull request merged**
