### PR TITLE
2441 add admin users

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
Proper admin users aka GOD ACCESS

### Changes proposed in this pull request
- Add boolean to existing user model
- Update pundit policy scopes to user new `user.admin?`

### Guidance to review
- Remove all organisations from current user
- Set `admin: true` on current user
- 🚢 

### Checklist
- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x]  Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by dankmitchell** [comment]
[Making actual super users](https://trello.com/c/pgJvJwh4/2441-making-actual-super-users)

**Comment by timabell** [comment]
Might be good to make the model invalid when the user is `admin: true` unless the user `email` address matches the old pattern. That would avoid us accidentally making a provider admin.

**Comment by davidgisbey** [comment]
I'm assuming this will be followed up by a migration to set users with @education and @digital emails to admins?

**Comment by dankmitchell** [comment]
> I'm assuming this will be followed up by a migration to set users with @education and @digital emails to admins?

That's one solution, yes @davidgisbey

**Comment by davidgisbey** [comment]
Looks good to me then!

**Comment by misaka** [comment]
Also, not that this would block an approval, but it seems `annotate` isn't running? Fixing that is probably a separate exercise, but maybe for now we could add the `admin` attribute to `course.rb` by hand?

**Pull request merged**
