### PR TITLE
Update schema from sanitized prod export

### PR DESCRIPTION
**Pull request by timabell**
I don't know if this is likely to cause issues, I don't entirely understand all the changes

I guess for review we need to make sure it works from clean.

### CODE REVIEW

**Comment by timabell** [comment]
```
...
-- create_table("organisation", {:id=>:integer, :default=>#<Proc:0x0000000004163268@/home/tim/repo/dfe/manage/backend/
db/schema.rb:95 (lambda)>, :force=>:cascade})
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "mc_organisation_id_seq" does not exist
: CREATE TABLE "organisation" ("id" integer DEFAULT nextval('mc_organisation_id_seq'::regclass) NOT NULL PRIMARY KEY, 
"name" text, "org_id" text)
/home/tim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql/database_state
ments.rb:75:in `async_exec'
...
```

**Comment by timabell** [comment]
https://stackoverflow.com/questions/2267922/how-do-i-use-migrations-to-create-a-postgres-sequence might hold the answer

**Comment by timabell** [comment]
We think the table name has drifted apart from the sequence names, resulting in the issue

**Comment by misaka** [comment]
Ya, I was just looking at all this to understand what's happening with these sequence definitions being set for the default id value (e.g. `default: -> { "nextval('mc_organisation_id_seq'::regclass)" },`). It looks like there's a miss-match between the table name and the sequence being used for the table's id, where perhaps the table name has been changed but not the name of the sequence.

Here's a table of each table and their sequence names with a suggested action we could do to bring it inline with Rails (maybe at a later time?).

| table                 | id sequence                        | notes         |
|-----------------------|------------------------------------|---------------|
| access_request        | access_request_id_seq              |               |
| course                | course_id_seq                      |               |
| course_enrichment     | course_enrichment_id_seq           |               |
| course_site           | course_site_id_seq                 |               |
| course_subject        | course_subject_id_seq              |               |
| nctl_organisation     | nctl_organisation_id_seq           | del if unused |
| organisation          | mc_organisation_id_seq             | rename        |
| organisation_provider | mc_organisation_institution_id_seq | rename        |
| organisation_user     | mc_organisation_user_id_seq        | rename        |
| pgde_course           | pgde_course_id_seq                 | del if unused |
| provider              | UcasInstitutions_Id_seq            | rename        |
| provider_enrichment   | institution_enrichment_id_seq      | rename        |
| session               | mc_session_id_seq                  | rename        |
| site                  | UcasCampuses_Id_seq                | rename        |
| subject               | UcasSubjects_Id_seq                | rename        |
| user                  | mc_user_id_seq                     | rename        |

**Comment by misaka** [comment]
For each of these we'd need to rename the sequence and also change the default id used by the table. My guess is to use something like this for each:

```
ALTER SEQUENCE mc_organisation_id_seq RENAME TO organisation_id_seq;
ALTER TABLE organisation ALTER id SET DEFAULT nextval('organisation_id_seq'::regclass);
```

**Comment by misaka** [comment]
I tested the SQL commands to rename a sequence and update the table and they appear to work, and to have the desired effect of reverting the sequence names to the defaults that Rails likes. Here's the full set of SQL commands we'd need to run for all the columns that need to be renamed.

```
ALTER SEQUENCE mc_organisation_id_seq RENAME TO organisation_id_seq;
ALTER TABLE organisation ALTER id SET DEFAULT nextval('organisation_id_seq'::regclass);

ALTER SEQUENCE mc_organisation_institution_id_seq RENAME TO organisation_provider_id_seq;
ALTER TABLE organisation_provider ALTER id SET DEFAULT nextval('organisation_provider_id_seq'::regclass);

ALTER SEQUENCE mc_organisation_user_id_seq RENAME TO organisation_user_id_seq;
ALTER TABLE organisation_user ALTER id SET DEFAULT nextval('organisation_user_id_seq'::regclass);

ALTER SEQUENCE UcasInstitutions_Id_seq RENAME TO provider_id_seq;
ALTER TABLE provider ALTER id SET DEFAULT nextval('provider_id_seq'::regclass);

ALTER SEQUENCE institution_enrichment_id_seq RENAME TO provider_enrichment_id_seq;
ALTER TABLE provider_enrichment ALTER id SET DEFAULT nextval('provider_enrichment_id_seq'::regclass);

ALTER SEQUENCE mc_session_id_seq RENAME TO session_id_seq;
ALTER TABLE session ALTER id SET DEFAULT nextval(session_id_seq'::regclass);

ALTER SEQUENCE UcasCampuses_Id_seq RENAME TO site_id_seq;
ALTER TABLE site ALTER id SET DEFAULT nextval(site_id_seq'::regclass);

ALTER SEQUENCE UcasSubjects_Id_seq RENAME TO subject_id_seq;
ALTER TABLE subject ALTER id SET DEFAULT nextval(subject_id_seq'::regclass);

ALTER SEQUENCE mc_user_id_seq RENAME TO user_id_seq;
ALTER TABLE user ALTER id SET DEFAULT nextval(user_id_seq'::regclass);
```

@timabell Could you check these and then we can make a plan for running them?

**Comment by timabell** [comment]
https://gist.github.com/timabell/503b2da4e4baa974c2726296e31be256 your script but with quoting fixed, got error running it so looking into that...

**Comment by timabell** [comment]
from copy of prod:
```
$ psql manage_courses_seq -c "SELECT c.relname FROM pg_class c WHERE c.relkind = 'S';"
              relname               
------------------------------------
 UcasCampuses_Id_seq
 access_request_id_seq
 UcasInstitutions_Id_seq
 UcasSubjects_Id_seq
 course_id_seq
 course_enrichment_id_seq
 course_subject_id_seq
 course_site_id_seq
 institution_enrichment_id_seq
 mc_organisation_id_seq
 mc_organisation_institution_id_seq
 mc_organisation_user_id_seq
 mc_session_id_seq
 mc_user_id_seq
 nctl_organisation_id_seq
 pgde_course_id_seq
(16 rows)
```

**Comment by timabell** [comment]
update script in gist now works, just a question of where to run it

**Comment by timabell** [comment]
schema.rb updated with result of `db:dump` having run the fixup sql locally

**Comment by timabell** [comment]
Migration for sequence names at https://github.com/DFE-Digital/manage-courses-api/pull/268

**Comment by timabell** [comment]
[Move DB migrations to Rails app.](https://trello.com/c/oYqWlNMY/961-move-db-migrations-to-rails-app)

**Comment by timabell** [comment]
Rebased & flattened. Re-did the schema dump because I got a merge conflict rebasing, but basically looks the same as before rebasing so going to merge this in.

**Pull request merged**
