### PR TITLE
[1682] remove data migrations

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
Headaches when migrations reply on data migrations and vise versa.

### Changes proposed in this pull request
Remove data migrations

### Guidance to review
n/a

### Checklist
- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by dankmitchell** [comment]
[Remove data migrations](https://trello.com/c/4haxChLF/1682-remove-data-migrations)

**Comment by misaka** [comment]
Why no MURG?

**Comment by dankmitchell** [comment]
Don't we need https://github.com/DFE-Digital/manage-courses-backend/pull/534 to be shipped first?

**Comment by misaka** [comment]
Ah. Well in any case it has now. I would've just burnt it with fire right away. 🔥

**Pull request merged**
