### PR TITLE
[2307] Add healthcheck endpoint

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
Ensure our app is up and running before pushing live

### Changes proposed in this pull request
Add [health_check](https://github.com/ianheggie/health_check) gem

To test -

```
curl -v -H "Accept: application/json" localhost:3001/healthcheck

...
HTTP/1.1 200 OK
...
```

Highly configurable - https://github.com/ianheggie/health_check#configuration

### Guidance to review
🚢 

### Checklist
- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by dankmitchell** [comment]
[add healthcheck endpoint to mcbe](https://trello.com/c/IKtCYGs0/2307-add-healthcheck-endpoint-to-mcbe)

**Comment by defong** [comment]
should we be using a gem that looks dead?
https://github.com/ianheggie/health_check/issues/94

verified that on master the tests passes

the two `unpermitted parameters` expected `raise_error(ActionController::UnpermittedParameters)`

**Comment by misaka** [comment]
I see your point about it being old and unmaintained, but I'm not sure that's an issue since it works for our needs (inc Rails 6). I also haven't found a decent alternative to implement, have you?

Sorry, but I don't understand your other points well enough to respond, pls clarify.

**Comment by misaka** [comment]
@rizzkhan1 Any idea why this is failing?

> ```
> Status: Downloaded newer image for postgres:9.6-alpine
> Creating s_db_1 ... 
>
> Creating s_db_1 ... ‌done‌
> Creating s_web_1 ... ‌
>
> Creating s_web_1 ... ‌done‌
> Creating s_bg-find-sync_1 ... ‌
>
> Creating s_bg-find-sync_1 ... ‌done‌
> Error response from daemon: Container b1fc3d8cdbd3ac9311c0fab1cc0846b4b3fdc2e4f273d03fdcc7efe99036cd32 is not running‌
> ##[error]Bash exited with code '1'.
> ##[section]Finishing: Build & setup
> ```

https://dfe-ssp.visualstudio.com/Become-A-Teacher/_build/results?buildId=25163

**Comment by misaka** [comment]
So turns out this gem somehow breaks strong params. Looking at the failing tests in CI, here's the behaviour when we access `params` with a disallowed param in it:

```
From: /Users/misaka/Code/DfE/manage-courses-backend/app/controllers/api/v2/sites_controller.rb @ line 21 API::V2::SitesController#create:

    19: def create
    20:   binding.pry
 => 21:   @site = @provider.sites.new(site_params)
    22:   authorize @site

[1] pry(#<API::V2::SitesController>)> params[:site][:code]
=> "FOO"
[2] pry(#<API::V2::SitesController>)> site_params
ActionController::UnpermittedParameters: found unpermitted parameter: :code
```

But with this gem an error isn't raised:

```
[1] pry(#<API::V2::SitesController>)> params[:site][:code]
=> "FOO"
[2] pry(#<API::V2::SitesController>)> site_params
=> <ActionController::Parameters {"location_name"=>"Main site 1", "address1"=>"4698 Timmy Shores", "address2"=>"Royal Heights", "address3"=>"Lake Elma", "address4"=>"Nevada", "postcode"=>"L6 5LL", "region_code"=>"london"} permitted: true>
```

We need to either opt for another gem or just use a simpler 'ping-pong' check.

**Pull request closed without merging**
